version: '2'
services:
    application:
        build: .
        volumes:
            - .:/var/www/symfony
        links:
            - mysql:mysql
        cached: true
    mysql:
        image: chaplean/mysql:mariadb10.1
        volumes:
            - mysql_data:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
            MYSQL_DATABASE: test_database
networks: {}
volumes:
    mysql_data: ~
